---
- name: Converge
  hosts: all
  become: true

  vars:
    # Role: yum_config_manager
    repositories:
      enabled:
        - rhui-REGION-rhel-server-rhscl
        - rhui-REGION-rhel-server-debug-rhscl

    # Role: nginx
    nginx_yum_repo_enabled: false
    nginx_use_scl: true
    nginx_package_name: rh-nginx18
    nginx_service_name: rh-nginx18-nginx
    nginx_conf_path: /etc/opt/rh/rh-nginx18/nginx/conf.d
    nginx_conf_file_path: /etc/opt/rh/rh-nginx18/nginx/nginx.conf
    nginx_mime_file_path: /etc/opt/rh/rh-nginx18/nginx/mime.types
    nginx_pid_file: /var/opt/rh/rh-nginx18/run/nginx/nginx.pid
    nginx_access_log: "/var/opt/rh/rh-nginx18/log/nginx/access.log main buffer=16k flush=2m"
    nginx_error_log: "/var/opt/rh/rh-nginx18/log/nginx/error.log warn"
    nginx_vhost_path: /etc/opt/rh/rh-nginx18/nginx/conf.d
    nginx_default_vhost_path: /etc/opt/rh/rh-nginx18/nginx/conf.d/default.conf
    nginx_vhosts:
      - listen: "80"
        server_name: "0.0.0.0"
        root: "/opt/rh/rh-nginx18/root/usr/share/nginx/html"
        index: "index.html index.htm"
        extra_parameters: |
          location ~* \.php$ {
            fastcgi_pass    127.0.0.1:9000;
            include         fastcgi_params;
            fastcgi_param   SCRIPT_FILENAME    $document_root$fastcgi_script_name;
            fastcgi_param   SCRIPT_NAME        $fastcgi_script_name;
          }

    # Role: php
    php_install_from_source: false
    php_scl_package: rh-php72
    php_use_scl: true
    php_enable_php_fpm: true
    php_webserver_daemon: "rh-nginx18-nginx"

  roles:
    - role: nycrecords.rhsm
    - role: nycrecords.nginx
    - role: ansible-role-php

  post_tasks:
    - name: Copy PHP info file
      copy:
        src: ../resources/test.php
        dest: /opt/rh/rh-nginx18/root/usr/share/nginx/html/test.php

